### ISSUE TITLE
Wifi Stack Error: wifi:Group & Pairwise ciphers must be AES-CCM for PMF

### ISSUE THREAD

**Issue by hmelder** [turgu1/EPub-InkPlate#12]
Connecting to the AP fails repeatedly with the following error: "wifi:Group & Pairwise ciphers must be AES-CCM for PMF"
<img width="1194" alt="Screenshot 2022-02-20 at 10 43 40" src="https://user-images.githubusercontent.com/45601940/154837188-3a1dc513-5184-4d76-9e9f-1e3f5d25852a.png">

**Comment by turgu1** [comment]
How is your wifi network configured for security? (WPA2, WPA3, RADIUS, PMF ? Other parameters beyond ssid and password?)

**Comment by hmelder** [comment]
I've checked the preferences of the AP and sure enough PMF was enabled. Thank you for the quick response :)

**Comment by turgu1** [comment]
Which security protocol are-you using, is it a router, what model?

**Comment by turgu1** [comment]
It may be that the PMF on your AP is using an opmode different than AES-CMM (like AES-GCM, CNSA, SAE-AES or others). Please try to find which one it is using.

**Comment by hmelder** [comment]
It works now. My router is a Vodafone EasyBox 804.
