### ISSUE TITLE
Font library problems - arduino

### ISSUE THREAD

**Issue by jie326513988** [turgu1/EPub-InkPlate#17]
Hello, your open source project is excellent.
I also have an open source ink screen project that needs TTF fonts, but it is the arduino platform. Can you tell me how to implement your TTF font library.

**Comment by turgu1** [comment]
Hello, thank you for the kind words!

The EPub-Inkplate is using Freetype version 2.10.4. There is newer versions of the library but  I can't tell if my recipe would work  for the new ones. The recipe is described in the main Readme.md file of the project: there is a section devoted to the specifics of building it for the EPub-Inkplate. 

Please note that the EPub-Inkplate has been built using the ESP-IDF SDK, not the Arduino. I can't tell if you would be successfull or not with it as I don' t have enough experience with the Arduino stuff to tell.

Good luck!
