### ISSUE TITLE
Feature request - text highlighting?

### ISSUE THREAD

**Issue by asterixorobelix** [turgu1/EPub-InkPlate#6]
First of all, many thanks for a great project! I plan on buying an inkplate purely because of this project!

I would just like to know, is text highlighting supported? I would like to use something like [readwise](https://readwise.io/) with this.

**Comment by turgu1** [comment]
Hello, this is a very interesting concept and it would certainly be possible to implement it using the email approach supported by readwise. The main issue is how to select phrases from a page. The current Inkplate-6 and Inkplate-10 are very limited to interact within the content of a page as they supply only 3 buttons and the screen is not tactile.

The upcoming Inkplate-6PLUS will be the answer as the screen is allowing for tactile interaction. I will put a note to look at this feature again when I will have completed my current round of update.

Thank you for shating this idea with me!
Cheers
Guy
